export enum Screens {
  STARTUP = "STARTUP",
  LOGIN = "LOGIN",
  HUB = "HUB",
  TOURNAMENT = "PLAY",
  ADVENTURE = "ADVENTURE",
  TAVERN_BRAWL = "TAVERN BRAWL",
  GAME_MODE = "MODES",
  DRAFT = "ARENA",
  BACON = "BATTLEGROUNDS",
  PVP_DUNGEON_RUN = "DUELS",
}